<?php

namespace Database\Seeders;

use App\Models\InventoryStoreItem;
use Illuminate\Database\Seeder;

class InventoryStoreItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'code' => 'INV-001',
                'name' => 'Towels (Bath)',
                'category' => 'Cleaning Supplies',
                'category_id' => 2,
                'stock' => 150,
                'min_stock' => 50,
                'unit' => 'pcs',
                'description' => 'Premium quality bath towels',
            ],
            [
                'code' => 'INV-002',
                'name' => 'Coffee Beans',
                'category' => 'Food & Beverages',
                'category_id' => 1,
                'stock' => 25,
                'min_stock' => 30,
                'unit' => 'kg',
                'description' => 'Premium arabica coffee beans',
            ],
            [
                'code' => 'INV-003',
                'name' => 'Toilet Paper',
                'category' => 'Cleaning Supplies',
                'category_id' => 2,
                'stock' => 0,
                'min_stock' => 20,
                'unit' => 'rolls',
                'description' => '2-ply toilet paper',
            ],
            [
                'code' => 'INV-004',
                'name' => 'Shampoo',
                'category' => 'Cleaning Supplies',
                'category_id' => 2,
                'stock' => 45,
                'min_stock' => 50,
                'unit' => 'bottles',
                'description' => 'Hotel-grade shampoo 500ml',
            ],
            [
                'code' => 'INV-005',
                'name' => 'Printer Paper',
                'category' => 'Office Supplies',
                'category_id' => 3,
                'stock' => 200,
                'min_stock' => 100,
                'unit' => 'reams',
                'description' => 'A4 size printer paper',
            ],
            [
                'code' => 'INV-006',
                'name' => 'Light Bulbs',
                'category' => 'Maintenance',
                'category_id' => 4,
                'stock' => 15,
                'min_stock' => 25,
                'unit' => 'pcs',
                'description' => 'LED light bulbs 12W',
            ],
            [
                'code' => 'INV-007',
                'name' => 'Bottled Water',
                'category' => 'Food & Beverages',
                'category_id' => 1,
                'stock' => 300,
                'min_stock' => 150,
                'unit' => 'bottles',
                'description' => '500ml bottled water',
            ],
            [
                'code' => 'INV-008',
                'name' => 'Soap Bars',
                'category' => 'Cleaning Supplies',
                'category_id' => 2,
                'stock' => 80,
                'min_stock' => 100,
                'unit' => 'pcs',
                'description' => 'Hotel soap bars',
            ],
            [
                'code' => 'INV-009',
                'name' => 'Pens',
                'category' => 'Office Supplies',
                'category_id' => 3,
                'stock' => 500,
                'min_stock' => 200,
                'unit' => 'pcs',
                'description' => 'Blue ink pens',
            ],
            [
                'code' => 'INV-010',
                'name' => 'Air Freshener',
                'category' => 'Cleaning Supplies',
                'category_id' => 2,
                'stock' => 30,
                'min_stock' => 20,
                'unit' => 'bottles',
                'description' => 'Room air freshener spray',
            ],
            [
                'code' => 'INV-011',
                'name' => 'Tea Bags',
                'category' => 'Food & Beverages',
                'category_id' => 1,
                'stock' => 120,
                'min_stock' => 80,
                'unit' => 'packs',
                'description' => 'Assorted tea bags',
            ],
            [
                'code' => 'INV-012',
                'name' => 'Batteries',
                'category' => 'Maintenance',
                'category_id' => 4,
                'stock' => 5,
                'min_stock' => 15,
                'unit' => 'packs',
                'description' => 'AA batteries pack of 4',
            ],
            [
                'code' => 'INV-013',
                'name' => 'Bed Sheets',
                'category' => 'Cleaning Supplies',
                'category_id' => 2,
                'stock' => 120,
                'min_stock' => 80,
                'unit' => 'sets',
                'description' => 'Premium cotton bed sheets',
            ],
            [
                'code' => 'INV-014',
                'name' => 'Sugar',
                'category' => 'Food & Beverages',
                'category_id' => 1,
                'stock' => 40,
                'min_stock' => 30,
                'unit' => 'kg',
                'description' => 'White granulated sugar',
            ],
            [
                'code' => 'INV-015',
                'name' => 'Notebooks',
                'category' => 'Office Supplies',
                'category_id' => 3,
                'stock' => 250,
                'min_stock' => 100,
                'unit' => 'pcs',
                'description' => 'A4 size notebooks',
            ],
            [
                'code' => 'INV-016',
                'name' => 'Paint',
                'category' => 'Maintenance',
                'category_id' => 4,
                'stock' => 20,
                'min_stock' => 15,
                'unit' => 'cans',
                'description' => 'White interior paint 5L',
            ],
            [
                'code' => 'INV-017',
                'name' => 'Milk',
                'category' => 'Food & Beverages',
                'category_id' => 1,
                'stock' => 60,
                'min_stock' => 40,
                'unit' => 'liters',
                'description' => 'Fresh whole milk',
            ],
            [
                'code' => 'INV-018',
                'name' => 'Trash Bags',
                'category' => 'Cleaning Supplies',
                'category_id' => 2,
                'stock' => 200,
                'min_stock' => 150,
                'unit' => 'rolls',
                'description' => 'Large trash bags 50L',
            ],
            [
                'code' => 'INV-019',
                'name' => 'Staples',
                'category' => 'Office Supplies',
                'category_id' => 3,
                'stock' => 100,
                'min_stock' => 50,
                'unit' => 'boxes',
                'description' => 'Standard staples for stapler',
            ],
            [
                'code' => 'INV-020',
                'name' => 'Wrench Set',
                'category' => 'Maintenance',
                'category_id' => 4,
                'stock' => 8,
                'min_stock' => 10,
                'unit' => 'sets',
                'description' => 'Professional wrench set',
            ],
            [
                'code' => 'INV-021',
                'name' => 'Orange Juice',
                'category' => 'Food & Beverages',
                'category_id' => 1,
                'stock' => 90,
                'min_stock' => 60,
                'unit' => 'bottles',
                'description' => 'Fresh orange juice 1L',
            ],
            [
                'code' => 'INV-022',
                'name' => 'Dish Soap',
                'category' => 'Cleaning Supplies',
                'category_id' => 2,
                'stock' => 35,
                'min_stock' => 40,
                'unit' => 'bottles',
                'description' => 'Liquid dish soap 750ml',
            ],
            [
                'code' => 'INV-023',
                'name' => 'Paper Clips',
                'category' => 'Office Supplies',
                'category_id' => 3,
                'stock' => 1500,
                'min_stock' => 500,
                'unit' => 'pcs',
                'description' => 'Standard paper clips',
            ],
            [
                'code' => 'INV-024',
                'name' => 'Screwdriver Set',
                'category' => 'Maintenance',
                'category_id' => 4,
                'stock' => 12,
                'min_stock' => 8,
                'unit' => 'sets',
                'description' => 'Multi-head screwdriver set',
            ],
        ];

        foreach ($items as $item) {
            InventoryStoreItem::updateOrCreate(
                ['code' => $item['code']],
                $item
            );
        }
    }
}

