<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'name' => 'ABC Trading Company',
                'company_name' => 'ABC Trading Co. Ltd.',
                'email' => 'contact@abctrading.com',
                'phone' => '+1-555-0101',
                'mobile' => '+1-555-0102',
                'address' => '123 Business Street',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'USA',
                'postal_code' => '10001',
                'contact_person' => 'John Smith',
                'tax_id' => 'TAX-ABC-001',
                'notes' => 'Primary supplier for cleaning supplies and office materials',
                'is_active' => true,
            ],
            [
                'name' => 'Global Food Supplies',
                'company_name' => 'Global Food Supplies Inc.',
                'email' => 'orders@globalfood.com',
                'phone' => '+1-555-0201',
                'mobile' => '+1-555-0202',
                'address' => '456 Market Avenue',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'country' => 'USA',
                'postal_code' => '90001',
                'contact_person' => 'Sarah Johnson',
                'tax_id' => 'TAX-GFS-002',
                'notes' => 'Specializes in food and beverage supplies',
                'is_active' => true,
            ],
            [
                'name' => 'Premium Linen Solutions',
                'company_name' => 'Premium Linen Solutions LLC',
                'email' => 'sales@premiumlinen.com',
                'phone' => '+1-555-0301',
                'mobile' => '+1-555-0302',
                'address' => '789 Textile Boulevard',
                'city' => 'Chicago',
                'state' => 'IL',
                'country' => 'USA',
                'postal_code' => '60601',
                'contact_person' => 'Michael Brown',
                'tax_id' => 'TAX-PLS-003',
                'notes' => 'Hotel-grade linens and towels supplier',
                'is_active' => true,
            ],
            [
                'name' => 'Tech Equipment Pro',
                'company_name' => 'Tech Equipment Professionals',
                'email' => 'info@techpro.com',
                'phone' => '+1-555-0401',
                'mobile' => '+1-555-0402',
                'address' => '321 Tech Park',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'postal_code' => '94101',
                'contact_person' => 'Emily Davis',
                'tax_id' => 'TAX-TEP-004',
                'notes' => 'Electronics and maintenance equipment',
                'is_active' => true,
            ],
            [
                'name' => 'Amenities Direct',
                'company_name' => 'Amenities Direct Supply Co.',
                'email' => 'orders@amenitiesdirect.com',
                'phone' => '+1-555-0501',
                'mobile' => '+1-555-0502',
                'address' => '654 Hospitality Lane',
                'city' => 'Miami',
                'state' => 'FL',
                'country' => 'USA',
                'postal_code' => '33101',
                'contact_person' => 'Robert Wilson',
                'tax_id' => 'TAX-ADS-005',
                'notes' => 'Bathroom amenities and consumables',
                'is_active' => true,
            ],
            [
                'name' => 'Maintenance Supplies Co.',
                'company_name' => 'Maintenance Supplies Company',
                'email' => 'sales@maintenancesupplies.com',
                'phone' => '+1-555-0601',
                'mobile' => '+1-555-0602',
                'address' => '987 Maintenance Road',
                'city' => 'Houston',
                'state' => 'TX',
                'country' => 'USA',
                'postal_code' => '77001',
                'contact_person' => 'Lisa Anderson',
                'tax_id' => 'TAX-MSC-006',
                'notes' => 'Tools and maintenance materials',
                'is_active' => true,
            ],
            [
                'name' => 'Office Essentials Plus',
                'company_name' => 'Office Essentials Plus Inc.',
                'email' => 'contact@officeplus.com',
                'phone' => '+1-555-0701',
                'mobile' => '+1-555-0702',
                'address' => '147 Office Plaza',
                'city' => 'Seattle',
                'state' => 'WA',
                'country' => 'USA',
                'postal_code' => '98101',
                'contact_person' => 'David Martinez',
                'tax_id' => 'TAX-OEP-007',
                'notes' => 'Office supplies and stationery',
                'is_active' => true,
            ],
            [
                'name' => 'Beverage Solutions',
                'company_name' => 'Beverage Solutions Ltd.',
                'email' => 'orders@beveragesolutions.com',
                'phone' => '+1-555-0801',
                'mobile' => '+1-555-0802',
                'address' => '258 Beverage Drive',
                'city' => 'Boston',
                'state' => 'MA',
                'country' => 'USA',
                'postal_code' => '02101',
                'contact_person' => 'Jennifer Taylor',
                'tax_id' => 'TAX-BSL-008',
                'notes' => 'Coffee, tea, and beverage supplies',
                'is_active' => true,
            ],
            [
                'name' => 'Housekeeping Supplies Pro',
                'company_name' => 'Housekeeping Supplies Professional',
                'email' => 'info@housekeepingpro.com',
                'phone' => '+1-555-0901',
                'mobile' => '+1-555-0902',
                'address' => '369 Service Street',
                'city' => 'Phoenix',
                'state' => 'AZ',
                'country' => 'USA',
                'postal_code' => '85001',
                'contact_person' => 'Christopher Lee',
                'tax_id' => 'TAX-HSP-009',
                'notes' => 'Housekeeping and cleaning products',
                'is_active' => true,
            ],
            [
                'name' => 'Furniture & Decor Inc.',
                'company_name' => 'Furniture & Decor Incorporated',
                'email' => 'sales@furnituredcor.com',
                'phone' => '+1-555-1001',
                'mobile' => '+1-555-1002',
                'address' => '741 Design Avenue',
                'city' => 'Atlanta',
                'state' => 'GA',
                'country' => 'USA',
                'postal_code' => '30301',
                'contact_person' => 'Amanda White',
                'tax_id' => 'TAX-FDI-010',
                'notes' => 'Furniture and decorative items',
                'is_active' => false,
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::create($supplier);
        }
    }
}
