// Comprehensive list of world timezones
export const timezones = [
    { value: 'UTC', label: 'UTC (Coordinated Universal Time)' },
    { value: 'America/New_York', label: 'America/New_York (EST/EDT)' },
    { value: 'America/Chicago', label: 'America/Chicago (CST/CDT)' },
    { value: 'America/Denver', label: 'America/Denver (MST/MDT)' },
    { value: 'America/Los_Angeles', label: 'America/Los_Angeles (PST/PDT)' },
    { value: 'America/Phoenix', label: 'America/Phoenix (MST)' },
    { value: 'America/Anchorage', label: 'America/Anchorage (AKST/AKDT)' },
    { value: 'America/Honolulu', label: 'America/Honolulu (HST)' },
    { value: 'America/Toronto', label: 'America/Toronto (EST/EDT)' },
    { value: 'America/Vancouver', label: 'America/Vancouver (PST/PDT)' },
    { value: 'America/Mexico_City', label: 'America/Mexico_City (CST/CDT)' },
    { value: 'America/Bogota', label: 'America/Bogota (COT)' },
    { value: 'America/Lima', label: 'America/Lima (PET)' },
    { value: 'America/Caracas', label: 'America/Caracas (VET)' },
    { value: 'America/Santiago', label: 'America/Santiago (CLT/CLST)' },
    { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo (BRT/BRST)' },
    { value: 'America/Buenos_Aires', label: 'America/Buenos_Aires (ART)' },
    { value: 'America/Montevideo', label: 'America/Montevideo (UYT)' },
    { value: 'America/Asuncion', label: 'America/Asuncion (PYT)' },
    { value: 'America/La_Paz', label: 'America/La_Paz (BOT)' },
    { value: 'America/Manaus', label: 'America/Manaus (AMT)' },
    { value: 'America/Cayenne', label: 'America/Cayenne (GFT)' },
    { value: 'America/St_Johns', label: 'America/St_Johns (NST/NDT)' },
    { value: 'America/Halifax', label: 'America/Halifax (AST/ADT)' },
    { value: 'America/Winnipeg', label: 'America/Winnipeg (CST/CDT)' },
    { value: 'America/Edmonton', label: 'America/Edmonton (MST/MDT)' },
    { value: 'America/Regina', label: 'America/Regina (CST)' },
    { value: 'America/Whitehorse', label: 'America/Whitehorse (PST/PDT)' },
    { value: 'America/Guatemala', label: 'America/Guatemala (CST)' },
    { value: 'America/El_Salvador', label: 'America/El_Salvador (CST)' },
    { value: 'America/Managua', label: 'America/Managua (CST)' },
    { value: 'America/Costa_Rica', label: 'America/Costa_Rica (CST)' },
    { value: 'America/Panama', label: 'America/Panama (EST)' },
    { value: 'America/Havana', label: 'America/Havana (CST/CDT)' },
    { value: 'America/Jamaica', label: 'America/Jamaica (EST)' },
    { value: 'America/Port-au-Prince', label: 'America/Port-au-Prince (EST/EDT)' },
    { value: 'America/Santo_Domingo', label: 'America/Santo_Domingo (AST)' },
    { value: 'America/Puerto_Rico', label: 'America/Puerto_Rico (AST)' },
    { value: 'America/Barbados', label: 'America/Barbados (AST)' },
    { value: 'America/Martinique', label: 'America/Martinique (AST)' },
    { value: 'America/Guadeloupe', label: 'America/Guadeloupe (AST)' },
    { value: 'Europe/London', label: 'Europe/London (GMT/BST)' },
    { value: 'Europe/Dublin', label: 'Europe/Dublin (GMT/IST)' },
    { value: 'Europe/Paris', label: 'Europe/Paris (CET/CEST)' },
    { value: 'Europe/Berlin', label: 'Europe/Berlin (CET/CEST)' },
    { value: 'Europe/Rome', label: 'Europe/Rome (CET/CEST)' },
    { value: 'Europe/Madrid', label: 'Europe/Madrid (CET/CEST)' },
    { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam (CET/CEST)' },
    { value: 'Europe/Brussels', label: 'Europe/Brussels (CET/CEST)' },
    { value: 'Europe/Vienna', label: 'Europe/Vienna (CET/CEST)' },
    { value: 'Europe/Zurich', label: 'Europe/Zurich (CET/CEST)' },
    { value: 'Europe/Stockholm', label: 'Europe/Stockholm (CET/CEST)' },
    { value: 'Europe/Oslo', label: 'Europe/Oslo (CET/CEST)' },
    { value: 'Europe/Copenhagen', label: 'Europe/Copenhagen (CET/CEST)' },
    { value: 'Europe/Helsinki', label: 'Europe/Helsinki (EET/EEST)' },
    { value: 'Europe/Athens', label: 'Europe/Athens (EET/EEST)' },
    { value: 'Europe/Warsaw', label: 'Europe/Warsaw (CET/CEST)' },
    { value: 'Europe/Prague', label: 'Europe/Prague (CET/CEST)' },
    { value: 'Europe/Budapest', label: 'Europe/Budapest (CET/CEST)' },
    { value: 'Europe/Bucharest', label: 'Europe/Bucharest (EET/EEST)' },
    { value: 'Europe/Sofia', label: 'Europe/Sofia (EET/EEST)' },
    { value: 'Europe/Kiev', label: 'Europe/Kiev (EET/EEST)' },
    { value: 'Europe/Moscow', label: 'Europe/Moscow (MSK)' },
    { value: 'Europe/Istanbul', label: 'Europe/Istanbul (TRT)' },
    { value: 'Europe/Lisbon', label: 'Europe/Lisbon (WET/WEST)' },
    { value: 'Europe/Madrid', label: 'Europe/Madrid (CET/CEST)' },
    { value: 'Europe/Rome', label: 'Europe/Rome (CET/CEST)' },
    { value: 'Europe/Belgrade', label: 'Europe/Belgrade (CET/CEST)' },
    { value: 'Europe/Zagreb', label: 'Europe/Zagreb (CET/CEST)' },
    { value: 'Europe/Sarajevo', label: 'Europe/Sarajevo (CET/CEST)' },
    { value: 'Europe/Skopje', label: 'Europe/Skopje (CET/CEST)' },
    { value: 'Europe/Tirane', label: 'Europe/Tirane (CET/CEST)' },
    { value: 'Europe/Riga', label: 'Europe/Riga (EET/EEST)' },
    { value: 'Europe/Tallinn', label: 'Europe/Tallinn (EET/EEST)' },
    { value: 'Europe/Vilnius', label: 'Europe/Vilnius (EET/EEST)' },
    { value: 'Asia/Dubai', label: 'Asia/Dubai (GST)' },
    { value: 'Asia/Kuwait', label: 'Asia/Kuwait (AST)' },
    { value: 'Asia/Bahrain', label: 'Asia/Bahrain (AST)' },
    { value: 'Asia/Qatar', label: 'Asia/Qatar (AST)' },
    { value: 'Asia/Muscat', label: 'Asia/Muscat (GST)' },
    { value: 'Asia/Riyadh', label: 'Asia/Riyadh (AST)' },
    { value: 'Asia/Tehran', label: 'Asia/Tehran (IRST)' },
    { value: 'Asia/Baghdad', label: 'Asia/Baghdad (AST)' },
    { value: 'Asia/Kuwait', label: 'Asia/Kuwait (AST)' },
    { value: 'Asia/Doha', label: 'Asia/Doha (AST)' },
    { value: 'Asia/Abu_Dhabi', label: 'Asia/Abu_Dhabi (GST)' },
    { value: 'Asia/Karachi', label: 'Asia/Karachi (PKT)' },
    { value: 'Asia/Islamabad', label: 'Asia/Islamabad (PKT)' },
    { value: 'Asia/Kolkata', label: 'Asia/Kolkata (IST)' },
    { value: 'Asia/Dhaka', label: 'Asia/Dhaka (BST)' },
    { value: 'Asia/Colombo', label: 'Asia/Colombo (IST)' },
    { value: 'Asia/Kathmandu', label: 'Asia/Kathmandu (NPT)' },
    { value: 'Asia/Thimphu', label: 'Asia/Thimphu (BTT)' },
    { value: 'Asia/Yangon', label: 'Asia/Yangon (MMT)' },
    { value: 'Asia/Bangkok', label: 'Asia/Bangkok (ICT)' },
    { value: 'Asia/Ho_Chi_Minh', label: 'Asia/Ho_Chi_Minh (ICT)' },
    { value: 'Asia/Phnom_Penh', label: 'Asia/Phnom_Penh (ICT)' },
    { value: 'Asia/Vientiane', label: 'Asia/Vientiane (ICT)' },
    { value: 'Asia/Jakarta', label: 'Asia/Jakarta (WIB)' },
    { value: 'Asia/Makassar', label: 'Asia/Makassar (WITA)' },
    { value: 'Asia/Jayapura', label: 'Asia/Jayapura (WIT)' },
    { value: 'Asia/Singapore', label: 'Asia/Singapore (SGT)' },
    { value: 'Asia/Kuala_Lumpur', label: 'Asia/Kuala_Lumpur (MYT)' },
    { value: 'Asia/Manila', label: 'Asia/Manila (PHT)' },
    { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong (HKT)' },
    { value: 'Asia/Taipei', label: 'Asia/Taipei (CST)' },
    { value: 'Asia/Shanghai', label: 'Asia/Shanghai (CST)' },
    { value: 'Asia/Beijing', label: 'Asia/Beijing (CST)' },
    { value: 'Asia/Urumqi', label: 'Asia/Urumqi (CST)' },
    { value: 'Asia/Seoul', label: 'Asia/Seoul (KST)' },
    { value: 'Asia/Tokyo', label: 'Asia/Tokyo (JST)' },
    { value: 'Asia/Vladivostok', label: 'Asia/Vladivostok (VLAT)' },
    { value: 'Asia/Yakutsk', label: 'Asia/Yakutsk (YAKT)' },
    { value: 'Asia/Irkutsk', label: 'Asia/Irkutsk (IRKT)' },
    { value: 'Asia/Krasnoyarsk', label: 'Asia/Krasnoyarsk (KRAT)' },
    { value: 'Asia/Yekaterinburg', label: 'Asia/Yekaterinburg (YEKT)' },
    { value: 'Asia/Tashkent', label: 'Asia/Tashkent (UZT)' },
    { value: 'Asia/Almaty', label: 'Asia/Almaty (ALMT)' },
    { value: 'Asia/Bishkek', label: 'Asia/Bishkek (KGT)' },
    { value: 'Asia/Dushanbe', label: 'Asia/Dushanbe (TJT)' },
    { value: 'Asia/Ashgabat', label: 'Asia/Ashgabat (TMT)' },
    { value: 'Asia/Kabul', label: 'Asia/Kabul (AFT)' },
    { value: 'Asia/Tbilisi', label: 'Asia/Tbilisi (GET)' },
    { value: 'Asia/Yerevan', label: 'Asia/Yerevan (AMT)' },
    { value: 'Asia/Baku', label: 'Asia/Baku (AZT)' },
    { value: 'Asia/Beirut', label: 'Asia/Beirut (EET/EEST)' },
    { value: 'Asia/Damascus', label: 'Asia/Damascus (EET/EEST)' },
    { value: 'Asia/Amman', label: 'Asia/Amman (EET/EEST)' },
    { value: 'Asia/Jerusalem', label: 'Asia/Jerusalem (IST/IDT)' },
    { value: 'Asia/Nicosia', label: 'Asia/Nicosia (EET/EEST)' },
    { value: 'Asia/Riyadh', label: 'Asia/Riyadh (AST)' },
    { value: 'Asia/Aden', label: 'Asia/Aden (AST)' },
    { value: 'Asia/Muscat', label: 'Asia/Muscat (GST)' },
    { value: 'Africa/Cairo', label: 'Africa/Cairo (EET/EEST)' },
    { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg (SAST)' },
    { value: 'Africa/Lagos', label: 'Africa/Lagos (WAT)' },
    { value: 'Africa/Nairobi', label: 'Africa/Nairobi (EAT)' },
    { value: 'Africa/Addis_Ababa', label: 'Africa/Addis_Ababa (EAT)' },
    { value: 'Africa/Dar_es_Salaam', label: 'Africa/Dar_es_Salaam (EAT)' },
    { value: 'Africa/Kampala', label: 'Africa/Kampala (EAT)' },
    { value: 'Africa/Kigali', label: 'Africa/Kigali (CAT)' },
    { value: 'Africa/Khartoum', label: 'Africa/Khartoum (CAT)' },
    { value: 'Africa/Juba', label: 'Africa/Juba (EAT)' },
    { value: 'Africa/Djibouti', label: 'Africa/Djibouti (EAT)' },
    { value: 'Africa/Mogadishu', label: 'Africa/Mogadishu (EAT)' },
    { value: 'Africa/Asmara', label: 'Africa/Asmara (EAT)' },
    { value: 'Africa/Casablanca', label: 'Africa/Casablanca (WET/WEST)' },
    { value: 'Africa/Algiers', label: 'Africa/Algiers (CET)' },
    { value: 'Africa/Tunis', label: 'Africa/Tunis (CET)' },
    { value: 'Africa/Tripoli', label: 'Africa/Tripoli (EET)' },
    { value: 'Africa/Accra', label: 'Africa/Accra (GMT)' },
    { value: 'Africa/Abidjan', label: 'Africa/Abidjan (GMT)' },
    { value: 'Africa/Dakar', label: 'Africa/Dakar (GMT)' },
    { value: 'Africa/Bamako', label: 'Africa/Bamako (GMT)' },
    { value: 'Africa/Conakry', label: 'Africa/Conakry (GMT)' },
    { value: 'Africa/Freetown', label: 'Africa/Freetown (GMT)' },
    { value: 'Africa/Monrovia', label: 'Africa/Monrovia (GMT)' },
    { value: 'Africa/Luanda', label: 'Africa/Luanda (WAT)' },
    { value: 'Africa/Kinshasa', label: 'Africa/Kinshasa (WAT)' },
    { value: 'Africa/Brazzaville', label: 'Africa/Brazzaville (WAT)' },
    { value: 'Africa/Douala', label: 'Africa/Douala (WAT)' },
    { value: 'Africa/Libreville', label: 'Africa/Libreville (WAT)' },
    { value: 'Africa/Malabo', label: 'Africa/Malabo (WAT)' },
    { value: 'Africa/Ndjamena', label: 'Africa/Ndjamena (WAT)' },
    { value: 'Africa/Bangui', label: 'Africa/Bangui (WAT)' },
    { value: 'Africa/Maputo', label: 'Africa/Maputo (CAT)' },
    { value: 'Africa/Harare', label: 'Africa/Harare (CAT)' },
    { value: 'Africa/Lusaka', label: 'Africa/Lusaka (CAT)' },
    { value: 'Africa/Blantyre', label: 'Africa/Blantyre (CAT)' },
    { value: 'Africa/Gaborone', label: 'Africa/Gaborone (CAT)' },
    { value: 'Africa/Windhoek', label: 'Africa/Windhoek (WAT)' },
    { value: 'Africa/Mbabane', label: 'Africa/Mbabane (SAST)' },
    { value: 'Africa/Maseru', label: 'Africa/Maseru (SAST)' },
    { value: 'Pacific/Auckland', label: 'Pacific/Auckland (NZST/NZDT)' },
    { value: 'Pacific/Chatham', label: 'Pacific/Chatham (CHAST/CHADT)' },
    { value: 'Pacific/Fiji', label: 'Pacific/Fiji (FJT/FJST)' },
    { value: 'Pacific/Guam', label: 'Pacific/Guam (ChST)' },
    { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu (HST)' },
    { value: 'Pacific/Port_Moresby', label: 'Pacific/Port_Moresby (PGT)' },
    { value: 'Pacific/Apia', label: 'Pacific/Apia (WST)' },
    { value: 'Pacific/Tongatapu', label: 'Pacific/Tongatapu (TOT)' },
    { value: 'Pacific/Noumea', label: 'Pacific/Noumea (NCT)' },
    { value: 'Pacific/Guadalcanal', label: 'Pacific/Guadalcanal (SBT)' },
    { value: 'Pacific/Port_Vila', label: 'Pacific/Port_Vila (VUT)' },
    { value: 'Pacific/Norfolk', label: 'Pacific/Norfolk (NFT)' },
    { value: 'Pacific/Pago_Pago', label: 'Pacific/Pago_Pago (SST)' },
    { value: 'Pacific/Majuro', label: 'Pacific/Majuro (MHT)' },
    { value: 'Pacific/Tarawa', label: 'Pacific/Tarawa (GILT)' },
    { value: 'Pacific/Funafuti', label: 'Pacific/Funafuti (TVT)' },
    { value: 'Pacific/Nauru', label: 'Pacific/Nauru (NRT)' },
    { value: 'Pacific/Palau', label: 'Pacific/Palau (PWT)' },
    { value: 'Pacific/Chuuk', label: 'Pacific/Chuuk (CHUT)' },
    { value: 'Pacific/Pohnpei', label: 'Pacific/Pohnpei (PONT)' },
    { value: 'Pacific/Kosrae', label: 'Pacific/Kosrae (KOST)' },
    { value: 'Pacific/Enderbury', label: 'Pacific/Enderbury (PHOT)' },
    { value: 'Pacific/Kiritimati', label: 'Pacific/Kiritimati (LINT)' },
    { value: 'Australia/Sydney', label: 'Australia/Sydney (AEST/AEDT)' },
    { value: 'Australia/Melbourne', label: 'Australia/Melbourne (AEST/AEDT)' },
    { value: 'Australia/Brisbane', label: 'Australia/Brisbane (AEST)' },
    { value: 'Australia/Adelaide', label: 'Australia/Adelaide (ACST/ACDT)' },
    { value: 'Australia/Perth', label: 'Australia/Perth (AWST)' },
    { value: 'Australia/Darwin', label: 'Australia/Darwin (ACST)' },
    { value: 'Australia/Hobart', label: 'Australia/Hobart (AEST/AEDT)' },
    { value: 'Australia/Canberra', label: 'Australia/Canberra (AEST/AEDT)' },
    { value: 'Antarctica/McMurdo', label: 'Antarctica/McMurdo (NZST/NZDT)' },
    { value: 'Antarctica/Casey', label: 'Antarctica/Casey (AWST)' },
    { value: 'Antarctica/Davis', label: 'Antarctica/Davis (DAVT)' },
    { value: 'Antarctica/Mawson', label: 'Antarctica/Mawson (MAWT)' },
    { value: 'Antarctica/Rothera', label: 'Antarctica/Rothera (ROTT)' },
    { value: 'Antarctica/Palmer', label: 'Antarctica/Palmer (CLT)' },
    { value: 'Antarctica/Troll', label: 'Antarctica/Troll (GMT)' },
];

// Get timezone by value
export function getTimezoneByValue(value) {
    return timezones.find(t => t.value === value) || timezones[0];
}

// Format date in timezone
export function formatDateInTimezone(date, timezone) {
    const options = {
        timeZone: timezone,
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hour12: false
    };
    return new Intl.DateTimeFormat('en-US', options).format(new Date(date));
}
